selected_plugins:
- EngineTest
- NI_DAQ
- CCP
- Calculated_Channels
- Channel_Manager
selected_displays:
- All Channels Table
- Main Test Monitor
data_root: C:/Projects/Python/Matrix_v2_retry/runs
test_cell: '0'
data_mode: real
imported_paths: []
