enabled: true
mode: real
recording_rate_hz: 10
session:
  interface: CAN1
  baudrate: 250000
  tx_id: '218059001'
  rx_id: '218059008'
  station_address: '0x0'
  is_extended: true
security:
  seed_resource: '1'
  seed_ctr: '7'
  connect_ctr: '25'
  unlock_ctr: '8'
  access_key: ''
  seed_endian: big
  sec_type: CAL
  unlock_pad: '85'
  force_unlock: true
  set_s_status: true
  s_status: '131'
a2l:
  path: C:/Projects/Python/Matrix_v2_retry/test files/a2l/v577/v577 Master_R2.a2l
poll_interval_ms: 10
poll_channels_per_tick: 1
io_timeout_s: 0.05
poll_default_priority: 100ms
acquisition_mode: daq
fallback_short_up: true
acquisition:
  mode: daq
  fallback_short_up: true
  seed_resource: '0x02'
  sec_type: DAQ
  tier: 100ms
  prescaler: 1
  daq_ena_address: '0x00147cef'
  daq_ena_value: 2
  max_odt_utilization_pct: 90
poll_endian: big
mta_addr_endian: big
addr_ext_high: false
reconnect_interval_s: 2.0
measurements:
  naming_prefix: emaster
  list: &id001
  - name: A_BM1
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: BP
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: CL_BM1
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: DBW_iFB_amps
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: EGO2_volts
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: HM_RAM_seconds
    unit_override: hours
    enabled: true
    priority: 100ms
    unit: hours
    address: 16782088
    address_extension: 0
    data_type: ULONG
    size: 4
    limits:
    - 0.0
    - 1193046.47083333
  - name: HM_RAMr_seconds
    unit_override: hours
    enabled: true
    priority: 100ms
    unit: hours
    address: 16790856
    address_extension: 0
    data_type: ULONG
    size: 4
    limits:
    - 0.0
    - 1193046.47083333
  - name: IAT
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: I_Gov3_acc
    unit_override: '%'
    enabled: true
    priority: 10ms
    unit: '%'
    address: 16783448
    address_extension: 0
    data_type: SLONG
    size: 4
    limits:
    - -800.0
    - 799.999999627471
  - name: KNK_retard
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: MAPressure
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: MAT
    unit_override: deg F
    enabled: true
    priority: 100ms
    unit: deg F
    address: 16777240
    address_extension: 0
    data_type: UWORD
    size: 2
    limits:
    - -460.0
    - 563.984375
  - name: MJ2_A_act
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: MJ2_P_act
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: MJ_A_act
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: MJ_A_cmd
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: MJ_P_act
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: MJ_P_cmd
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: OILP_press
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: OILT
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: Phi_UEGO
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: TIP
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: TPS1_pct
    unit_override: ''
    enabled: true
    priority: 50ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: TPS2_pct
    unit_override: ''
    enabled: true
    priority: 50ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: TPS_cmd_pct
    unit_override: ''
    enabled: true
    priority: 50ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: Vbat
    unit_override: ''
    enabled: true
    priority: 50ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: Vsw
    unit_override: ''
    enabled: true
    priority: 50ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: bst_Ptarg_P
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: bst_WGAcmd_DC
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: bst_WGAcmd_V
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: bst_WGPa
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: bst_loadcmd
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: eng_load
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: gov_MAP_d
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: mdot_a_ports
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: mdot_f_ports
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: rECT
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: rpm
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: rpmd_gain
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: rpmd_gov
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
  - name: run_mode
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: UBYTE
    size: 1
  - name: spk_adv
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SWORD
    size: 2
  - name: sync_state
    unit_override: ''
    enabled: true
    priority: 10ms
    unit: ''
    data_type: SBYTE
    size: 1
  - name: torque_Nm_gross
    unit_override: ''
    enabled: true
    priority: 100ms
    unit: ''
    data_type: UWORD
    size: 2
writes: []
devices:
- name: CCP Primary
  role: primary
  session:
    interface: CAN1
    baudrate: 250000
    tx_id: '218059001'
    rx_id: '218059008'
    station_address: '0x0'
    is_extended: true
  security:
    seed_resource: '1'
    seed_ctr: '7'
    connect_ctr: '25'
    unlock_ctr: '8'
    access_key: ''
    seed_endian: big
    sec_type: CAL
    unlock_pad: '85'
    force_unlock: true
    set_s_status: true
    s_status: '131'
  a2l:
    path: C:/Projects/Python/Matrix_v2_retry/test files/a2l/v577/v577 Master_R2.a2l
  poll_interval_ms: 10
  acquisition_mode: daq
  fallback_short_up: true
  acquisition:
    mode: daq
    fallback_short_up: true
    seed_resource: '0x02'
    sec_type: DAQ
    tier: 100ms
    prescaler: 1
    daq_ena_address: '0x00147cef'
    daq_ena_value: 2
    max_odt_utilization_pct: 90
  poll_default_priority: 100ms
  measurements:
    naming_prefix: emaster
    list: *id001
