enabled: true
recording_rate_hz: 50.0
channels:
- name: EstopLogic
  enabled: true
  symbols:
    rpm: cSP_Eng
    softalarm: iOT_AlmSftSdn
    estop: qDG_FacEspAct
  body: 'softsd = 1 if (softalarm == 1 and rpm == 0) else 0

    estopstatus = 0 if (softsd == 1 or estop == 0) else 1

    estoplight = 0 if (softsd == 1) else 1

    fuellockoff = 0 if (estop == 0) else 1


    '
  outputs:
  - var: softsd
    alias: mOT_EngSsd
    unit: bool
  - var: fuellockoff
    alias: eFuelLockoffStatus
    unit: bool
  - var: estopstatus
    alias: mDG_GenEspAct
    unit: bool
  - var: estoplight
    alias: mDG_FacSsdEspAct
    unit: bool
- name: J1995 Power Correction
  enabled: true
  symbols:
    baro: qPR_Amb
    temp: qTP_Amb
    rh: vRH_Amb
    bp: lPO_LdbPwr
  body: '#Convert observed power to corrected power


    #Convert temps to K and pressure to Pa

    tempK = temp + 273.15

    baroPa = baro*1000


    #Saturated water vapor pressure

    #https://www.engineeringtoolbox.com/water-vapor-saturation-pressure-air-d_689.html

    psx = (exp(77.345+0.0057*tempK-7235/tempK)/(tempK**8.2))


    #Dry air inlet pressure

    bdo = baroPa - rh*psx


    #Correction Factor

    CF = 1.18*((99000/bdo)*((tempK)/298)**0.5)-0.18


    #Corrected Power

    bpc = CF*bp'
  outputs:
  - var: CF
    alias: xPO_CF
    unit: ''
  - var: bpc
    alias: mPO_PwrCor
    unit: kW
- name: WP17 Mech Power
  enabled: true
  symbols:
    pwr: xPO_GenAvg
    frq: xFQ_Gen
    speed: emasterrpm
  body: 'alteff = (-0.00018407 * pwr ** 2 + 0.0858 * pwr) if (38 <= frq <= 54.999)
    else ((-0.00006868 * pwr ** 2 + 0.04685112 * pwr + 88.44023169) if (55 <= frq
    <= 65) else 0)


    fanpwr = 16.49 if (38 <= frq <= 54.999) else (31 if (55 <= frq <= 65) else 0)


    altpwr = (1 - (alteff * 0.01)) * pwr

    engalt = 2.28

    mechpwr = kwe + fanpwr + altpwr + engalt

    mechtrq = (mechpwr * 9548.8) / speed if speed != 0 else 0

    pi = 3.141592653589793

    bmep = (mechtrq * 4 * pi) / 1670'
  outputs:
  - var: alteff
    alias: mPC_AltAct
    unit: frac
  - var: fanpwr
    alias: mPO_Fan
    unit: kWe
  - var: altpwr
    alias: mPO_Alt
    unit: kWe
  - var: mechpwr
    alias: mPO_Eng
    unit: kWm
  - var: mechtrq
    alias: mTQ_Eng
    unit: Nm
  - var: bmep
    alias: xPO_BMEPRAW
    unit: Bar
- name: CyclePlayLogic
  enabled: true
  symbols:
    time: iTM_Tst
  body: cycle_play = 1 if time > 250 else 0
  outputs:
  - var: cycle_play
    alias: iCycle_Play
    unit: bool
