enabled: true
mode: real
recording_rate_hz: 10
session:
  interface: CAN1
  baudrate: 250000
  tx_id: '218059001'
  rx_id: '218059008'
  station_address: '0x0'
  is_extended: true
security:
  seed_resource: '1'
  seed_ctr: '7'
  connect_ctr: '25'
  unlock_ctr: '8'
  access_key: ''
  seed_endian: big
  sec_type: CAL
  unlock_pad: '85'
  force_unlock: true
  set_s_status: true
  s_status: '131'
a2l:
  path: C:/Projects/Python/Matrix_v2_retry/test files/a2l/v577/v577 Master_R2.a2l
poll_interval_ms: 10
poll_channels_per_tick: 1
io_timeout_s: 0.06
short_up_timeout_s: 0.04
short_up_debug_misses: false
poll_default_priority: low
target_poll_hz: 5
acquisition_mode: short_up
fallback_short_up: false
acquisition:
  mode: short_up
  fallback_short_up: false
  seed_resource: '0x02'
  sec_type: DAQ
  tier: 100ms
  prescaler: 1
  daq_ena_address: '0x00147cef'
  daq_ena_value: 2
  max_odt_utilization_pct: 90
poll_endian: big
mta_addr_endian: big
addr_ext_high: false
reconnect_interval_s: 2.0
measurements:
  naming_prefix: emaster
  list: &id001
  - name: TIPAdaptTbl
    unit_override: TIP Correction (%)
    enabled: true
    priority: low
    unit: TIP Correction (%)
    address: 37298176
    data_type: SWORD
    size: 2
    limits:
    - -100.0
    - 99.9969482421875
  - name: TIPAdapt_ECT_mstr
    unit_override: deg F
    enabled: true
    priority: low
    unit: deg F
    address: 16830936
    data_type: UWORD
    size: 2
    limits:
    - -460.0
    - 563.984375
  - name: TIPAdapt_ECT_slv
    unit_override: deg F
    enabled: true
    priority: low
    unit: deg F
    address: 16830944
    data_type: UWORD
    size: 2
    limits:
    - -460.0
    - 563.984375
  - name: TIPAdapt_MAP_LPmstr
    unit_override: psia
    enabled: true
    priority: low
    unit: psia
    address: 16830888
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: TIPAdapt_MAP_LPslv
    unit_override: psia
    enabled: true
    priority: low
    unit: psia
    address: 16830896
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: TIPAdapt_MAP_mstr
    unit_override: psia
    enabled: true
    priority: low
    unit: psia
    address: 16830904
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: TIPAdapt_MAP_slv
    unit_override: psia
    enabled: true
    priority: low
    unit: psia
    address: 16830912
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: TIPAdapt_MAPerror
    unit_override: psi
    enabled: true
    priority: low
    unit: psi
    address: 16831800
    data_type: SWORD
    size: 2
    limits:
    - -128.0
    - 127.99609375
  - name: TIPAdapt_TIP_mstr
    unit_override: psi
    enabled: true
    priority: low
    unit: psi
    address: 16832080
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: TIPAdapt_TIP_slv
    unit_override: psi
    enabled: true
    priority: low
    unit: psi
    address: 16832088
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: TIPAdapt_TIPcorrect
    unit_override: TIP %
    enabled: true
    priority: low
    unit: TIP %
    address: 16832096
    data_type: SWORD
    size: 2
    limits:
    - -100.0
    - 99.9969482421875
  - name: TIPAdapt_cmd_final
    unit_override: '% TPS'
    enabled: true
    priority: low
    unit: '% TPS'
    address: 16831040
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 99.9984741210938
  - name: TIPAdapt_cmd_mstr
    unit_override: '% TPS'
    enabled: true
    priority: low
    unit: '% TPS'
    address: 16830920
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 99.9984741210938
  - name: TIPAdapt_cmd_slv
    unit_override: '% TPS'
    enabled: true
    priority: low
    unit: '% TPS'
    address: 16830928
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 99.9984741210938
  - name: TIPAdapt_correction
    unit_override: '% TPS'
    enabled: true
    priority: low
    unit: '% TPS'
    address: 16830880
    data_type: SWORD
    size: 2
    limits:
    - -100.0
    - 99.9969482421875
  - name: TIPAdapt_tblcorrect
    unit_override: '% TPS'
    enabled: true
    priority: low
    unit: '% TPS'
    address: 16831792
    data_type: SWORD
    size: 2
    limits:
    - -100.0
    - 99.9969482421875
  - name: Vbat
    unit_override: volts
    enabled: true
    priority: low
    unit: volts
    address: 16777568
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
  - name: Vsw
    unit_override: volts
    enabled: true
    priority: low
    unit: volts
    address: 16777576
    data_type: UWORD
    size: 2
    limits:
    - 0.0
    - 255.99609375
writes: []
devices:
- name: CCP Primary
  role: primary
  session:
    interface: CAN1
    baudrate: 250000
    tx_id: '218059001'
    rx_id: '218059008'
    station_address: '0x0'
    is_extended: true
  security:
    seed_resource: '1'
    seed_ctr: '7'
    connect_ctr: '25'
    unlock_ctr: '8'
    access_key: ''
    seed_endian: big
    sec_type: CAL
    unlock_pad: '85'
    force_unlock: true
    set_s_status: true
    s_status: '131'
  a2l:
    path: C:/Projects/Python/Matrix_v2_retry/test files/a2l/v577/v577 Master_R2.a2l
  poll_interval_ms: 10
  acquisition_mode: short_up
  fallback_short_up: false
  acquisition:
    mode: short_up
    fallback_short_up: false
    seed_resource: '0x02'
    sec_type: DAQ
    tier: 100ms
    prescaler: 1
    daq_ena_address: '0x00147cef'
    daq_ena_value: 2
    max_odt_utilization_pct: 90
  poll_default_priority: low
  measurements:
    naming_prefix: emaster
    list: *id001
