source:
  csv_path: C:/Users/tonkst/Desktop/cycletest - Copy.csv
execution:
  loops_total: 1
  start_with_test: false
outputs:
- csv_column: ignition
  type: nidaq_ao
  alias: xIgnition
- csv_column: louverposition
  type: nidaq_ao
  alias: eLOUVERPosition
