selected_plugins:
- Cycle
- LoadBank
- EngineTest
- Channel_Manager
- Calculated_Channels
- NI_DAQ
selected_displays:
- All Channels Table
data_root: C:/Projects/Python/Matrix_v2_retry/runs
test_cell: '0'
data_mode: real
imported_paths: []
