selected_plugins:
- Channel_Manager
- Cycle
- EngineTest
- Calculated_Channels
- NI_DAQ
- LoadBank
selected_displays:
- All Channels Table
data_root: C:/Projects/Python/Matrix_v2_retry/runs
test_cell: '0'
data_mode: real
imported_paths: []
