selected_plugins:
- Cycle
- NI_DAQ
- EngineTest
- Channel_Manager
- LoadBank
- Calculated_Channels
selected_displays:
- All Channels Table
data_root: C:/Projects/Python/Matrix_v2_retry/runs
test_cell: '0'
data_mode: real
imported_paths: []
